compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      fflags: -D__CRAY_FORTRAN__
    modules:
    - cce/8.7.7
    operating_system: rhel7
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@8.7.7
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      fflags: -D__CRAY_FORTRAN__
    modules:
    - cce/8.6.5
    operating_system: rhel7
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@8.6.5
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - gcc/6.1.0
    operating_system: rhel7
    paths:
      cc: gcc
      cxx: g++
      f77: gfortran
      fc: gfortran
    spec: gcc@6.1.0
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - gcc/7.2.0
    operating_system: rhel7
    paths:
      cc: gcc
      cxx: g++
      f77: gfortran
      fc: gfortran
    spec: gcc@7.2.0
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
      - PrgEnv-gnu/18.12
      - gcc/7.4.0-2.31.1
    operating_system: rhel7
    paths:
      cc: gcc
      cxx: g++
      f77: gfortran
      fc: gfortran
    spec: gcc@7.4.0
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-pgi/18.10
    - pgi/18.10-gcc-7.4.0-2.31.1
    operating_system: rhel7
    paths:
      cc: gcc
      cxx: g++
      f77: gfortran
      fc: gfortran
    spec: pgi@18.10
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-pgi/19.4
    - pgi/19.4-gcc-7.4.0-2.31.1
    operating_system: rhel7
    paths:
      cc: gcc
      cxx: g++
      f77: gfortran
      fc: gfortran
    spec: pgi@19.4
    target: any
