compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-gnu/19.2
    operating_system: rhel7
    paths:
      cc: gcc
      cxx: g++
      f77: gfortran
      fc: gfortran
    spec: gcc@8.3.0
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-pgi/19.9
    operating_system: rhel7
    paths:
      cc: mpicc
      cxx: mpic++
      f77: mpif77
      fc: pgfortran
    spec: pgi@19.9
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-pgi/19.9
    operating_system: rhel7
    paths:
      cc: mpicc
      cxx: mpic++
      f77: mpif77
      fc: mpif90
    spec: pgi@19.9-gcc@8.3.0
    target: any
