compilers::
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - /apps/arolla/UES/jenkins/RH7.6/pgi/19.9/easybuild/modules/all/pgi/19.9-gcc-8.3.0
    operating_system: rhel7
    paths:
      cc: pgcc
      cxx: pgc++
      f77: pgfortran
      fc: pgfortran
    spec: pgi@19.9
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: 
    - gcc/8.3.0
    operating_system: rhel7
    paths:
      cc: gcc
      cxx: g++
      f77: gfortran
      fc: gfortran
    spec: gcc@8.3.0-nomod
    target: any
