config:
  install_tree: /project/g110/spack-test/install/tsa #to be changed to project/c14/install/tsa
  template_dirs:
    - $spack/templates
  module_roots:
    tcl:  /project/g110/spack-test/modules/ #to be changed to ?
  build_stage:
    - /scratch/$user/spack-stages/tsa
  install_path_scheme: '{name}/{version}/{compiler.name}'
