config:
  parameters:
    install_path: &install_path /scratch/egermann/install/tsa #to be changed to project/c14/install/tsa
    modules_install_path: &modules_install_path /scratch/egermann/modules/ #to be changed to ?
  install_tree: *install_path
  template_dirs:
    - $spack/templates
  module_roots:
    tcl:  *modules_install_path
  build_stage:
    - $spack/var/spack/stage
  install_path_scheme: '{name}/{version}/{compiler.name}'
