config:
  install_tree: /project/g110/spack-install/tsa #to be changed to project/c14/install/daint
  template_dirs:
    - $spack/templates
  module_roots:
    tcl:  /project/g110/spack-modules/tsa
  build_stage:
    - /project/g110/spack-stages/tsa
  install_path_scheme: '{name}/{version}/{compiler.name}/{hash}'
