packages:
  all:
    compiler: [pgi@19.9, pgi@19.9-gcc, gcc]
  cmake:
    modules:
      cmake@3.14.5: cmake/3.14.5
    buildable: true
    version: [3.14.5]
    target: []
    providers: {}
    compiler: []
    paths: {}
  boost:
    paths:
      boost@1.71.0: /project/c14/install/arolla/boost/boost_1_71_0/
      boost@1.67.0: /project/c14/install/arolla/boost/boost_1_67_0/
      boost@1.64.0: /project/c14/install/arolla/boost/boost_1_64_0/
    buildable: true
    version: []
    target: []
    providers: {}
    modules: {}
    compiler: []
  cuda:
    modules:
      cuda@10.1.243: cuda/10.1.243
    buildable: true
    version: []
    target: []
    providers: {}
    paths: {}
    compiler: []
  ncurses:
    compiler: [gcc]
  grib-api:
    version: [1.20.0.2]
  openmpi:
    paths:
      openmpi@4.0.2: /apps/arolla/UES/jenkins/RH7.6/pgi/19.9/easybuild/software/OpenMPI/4.0.2-PGI-19.9-GCC-8.3.0-cuda-10.1
    compiler: [pgi]
  openmpi:
    paths:
      openmpi@4.0.2: /apps/arolla/UES/jenkins/RH7.6/gnu/19.2/easybuild/software/OpenMPI/4.0.2-gcccuda-2019b-cuda-10.1
    compiler: [gcc]
  netcdf-fortran:
    paths:
      netcdf-fortran@4.4.5: /apps/arolla/UES/jenkins/RH7.6/pgi/19.9/easybuild/software/netCDF-Fortran/4.4.5-PGI-19.9-GCC-8.3.0
  netcdf-c:
    paths:
      netcdf-c@4.7.0 : /apps/arolla/UES/jenkins/RH7.6/pgi/19.9/easybuild/software/netCDF/4.7.0-PGI-19.9-GCC-8.3.0
