packages:
  all:
    compiler: [pgi@19.9, pgi@19.9-gcc, gcc]
  cmake:
    modules:
      cmake@3.14.5: cmake/3.14.5
    buildable: true
    version: [3.14.5]
    target: []
    providers: {}
    compiler: []
    paths: {}
  boost:
    paths:
      boost@1.71.0: /project/c14/install/arolla/boost/boost_1_71_0/
      boost@1.67.0: /project/c14/install/arolla/boost/boost_1_67_0/
      boost@1.64.0: /project/c14/install/arolla/boost/boost_1_64_0/
    buildable: true
    version: []
    target: []
    providers: {}
    modules: {}
    compiler: []
  cuda:
    modules:
      cuda@10.1.243%pgi: PrgEnv-pgi/19.9
      cuda@10.1.243%gcc: PrgEnv-gnu/19.2
    buildable: true
    version: []
    target: []
    providers: {}
    paths: {}
  openmpi:
    paths:
      openmpi@4.0.2%pgi: /apps/arolla/UES/jenkins/RH7.6/pgi/19.9/easybuild/software/OpenMPI/4.0.2-PGI-19.9-GCC-8.3.0-cuda-10.1
      openmpi@4.0.2%gcc: /apps/arolla/UES/jenkins/RH7.6/gnu/19.2/easybuild/software/OpenMPI/4.0.2-gcccuda-2019b-cuda-10.1
  netcdf-fortran:
    paths:
      netcdf-fortran@4.4.5%pgi: /apps/arolla/UES/jenkins/RH7.6/pgi/19.9/easybuild/software/netCDF-Fortran/4.4.5-PGI-19.9-GCC-8.3.0
      netcdf-fortran@4.4.5%gcc: /apps/arolla/UES/jenkins/RH7.6/gnu/19.2/easybuild/software/netCDF-Fortran/4.4.5-fosscuda-2019b/include
  netcdf-c:
    paths:
      netcdf-c@4.7.0%pgi : /apps/arolla/UES/jenkins/RH7.6/pgi/19.9/easybuild/software/netCDF/4.7.0-PGI-19.9-GCC-8.3.0
      netcdf-c@4.7.0%gcc : /apps/arolla/UES/jenkins/RH7.6/gnu/19.2/easybuild/software/netCDF/4.7.0-fosscuda-2019b/include
  perl:
    paths: 
      perl@5.16.3: /usr
  m4:
    paths: 
      m4@1.4.16: /usr
  automake:
    paths:
      automake@1.13.4: /usr
  libtool:
    paths:
      libtool@2.4.2: /usr
  autoconf:
    paths:
      autoconf@2.69: /usr
  bison:
    paths:
      bison@3.0.4: /usr
  ncurses:
    paths:
      ncurses@6.1: /usr
  libxml2:
    paths:
      libxml2@2.9.9: /usr
  libjpeg:
    paths:
      libjpeg: /usr
  slurm:
    modules:
      slurm@19.05.04: slurm/19.05.04
  cosmo-dycore:
    variants: cuda_arch=sm_70
    compiler: [gcc]
  gridtools:
    variants: cuda_arch=sm_70
    compiler: [gcc]
  cosmo:
    version: [master]
    compiler: [pgi]

