compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-cray/6.0.5
    operating_system: cnl7
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@9.0.2
    target: any

