compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      fflags: -D__CRAY_FORTRAN__
    modules:
    - cce/8.7.9
    operating_system: rhel7
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@8.7.9
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      fflags: -D__CRAY_FORTRAN__
    modules:
    - cce/9.0.2
    operating_system: rhel7
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@9.0.2
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - gcc/6.1.0
    operating_system: rhel7
    paths:
      cc: gcc
      cxx: g++
      f77: gfortran
      fc: gfortran
    spec: gcc@6.1.0
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - gcc/7.2.0
    operating_system: rhel7
    paths:
      cc: gcc
      cxx: g++
      f77: gfortran
      fc: gfortran
    spec: gcc@7.2.0
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - gcc/7.3.0
    operating_system: rhel7
    paths:
      cc: gcc
      cxx: g++
      f77: gfortran
      fc: gfortran
    spec: gcc@7.3.0
    target: any- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - gcc/7.3.0
    operating_system: rhel7
    paths:
      cc: gcc
      cxx: g++
      f77: gfortran
      fc: gfortran
    spec: gcc@7.3.0
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - gcc/8.2.0
    operating_system: rhel7
    paths:
      cc: gcc
      cxx: g++
      f77: gfortran
      fc: gfortran
    spec: gcc@8.2.0
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-pgi/6.0.5
    operating_system: rhel7
    paths:
      cc: pgcc
      cxx: pgc++
      f77: pgfortran
      fc: pgfortran
    spec: pgi@19.7.0
    target: any
