config:
  install_tree: /project/g110/spack-test/install/daint #to be changed to project/g110/install/daint
  template_dirs:
    - $spack/templates
  module_roots:
    tcl:  /project/g110/spack-test/modules/
  build_stage:
    - /scratch/snx3000/$user/spack-stages/daint
  install_path_scheme: '{name}/{version}/{compiler.name}'
