modules:
  enable:
    - tcl
  tcl: 
    all:
      autoload: 'direct'
    naming_scheme: '${PACKAGE}/${VERSION}'
    hash_length: 0
    blacklist: ['cuda', 'cmake', 'slurm']
    boost:
      environment:
        set:
          BOOST_ROOT: '${PREFIX}'
    gridtools:
      environment:
        set:
          GRIDTOOLS_DIR: '${PREFIX}'
          GRIDTOOLS_ROOT: '${PREFIX}' 
    cosmo-dycore:
      environment:
        set:
          DYCOREGT_DIR: '${PREFIX}'
          UCX_MEMTYPE_CACHE: 'n'
          UCX_TLS: 'rc_x,ud_x,mm,shm,cuda_copy,cuda_ipc,cm'
          MPICH_G2G_PIPELINE: '64'
          MPICH_RDMA_ENABLED_CUDA: '1'

    serialbox:
      environment:
        set:
          SERIALBOX_DIR: '${PREFIX}'
          SERIALBOX_ROOT: '${PREFIX}'
    claw:
      environment:
        set:
          CLAWDIR: '${PREFIX}'
          CLAWFC: '${PREFIX}/bin/clawfc'
          CLAWXMODSPOOL: '/project/c14/install/omni-xmod-pool/'
    ant:
      environment:
        set:
         ANT_HOME: '${PREFIX}'
    bison:
      environment:
        set:
          YACC: 'bison -y'
