packages:
  all:
    compiler: []
  serialbox:
    compiler: [gcc@8.3.0]
    buildable: true
    version: [2.5.4]
    target: []
    providers: {}
    paths: {}
    modules: {}
  cmake:
    paths:
      cmake@3.14.5: /apps/daint/UES/jenkins/7.0.UP01/gpu/easybuild/software/CMake/3.14.5
    buildable: true
    version: []
    target: []
    providers: {}
    compiler: []
  boost:
    paths:
      boost@1.71.0: /project/g110/install/daint/boost/boost_1_71_0
    buildable: true
    version: []
    target: []
    providers: {}
    modules: {}
    compiler: []
  cuda:
    modules:
      cuda@10.1.105_3: cudatoolkit/10.1.105_3.27-7.0.1.1_4.1__ga311ce7
    buildable: true
    version: []
    target: []
    providers: {}
    paths: {}
    compiler: []
  ncurses:
    compiler: [gcc]
  grib-api:
    version: [1.20.0.2]
  mpich:
    modules:
      mpich@7.7.10: cray-mpich/7.7.10
      mpich@7.7.9: cray-mpich/7.7.9
      mpich@7.7.6: cray-mpich/7.7.6
  netcdf:
    modules:
      cray-netcdf@4.6.3.1: cray-netcdf/4.6.3.1
    compiler: [cce] 
  perl:
    paths: 
      perl: /usr
  m4:
    paths: 
      m4: /usr
  automake:
    paths:
      automake: /usr
  libtool:
    paths:
      libtool: /usr
  autoconf:
    paths:
      autoconf: /usr
  bison:
    paths:
      bison: /usr
  ncurses:
    paths:
      ncurses: /usr
  jasper:
    paths:
      jasper: /usr
  ant:
    paths:
      ant: /usr
  libxml2:
    paths:
      libxml2: /usr
  openjdk:
    paths:
      openjdk: /usr
  slurm:
    modules:
      slurm@19.05.3-2: slurm/19.05.3-2
  gridtools:
    variants: cuda_arch=sm_60
    compiler: [gcc]      
  cosmo-dycore:
    variants: cuda_arch=sm_60
    compiler: [gcc]
